#!/usr/bin/perl
# homelab-backup-lib.pl - Helper library for Homelab Backup 3-2-1-1-0 Webmin Module

BEGIN { push(@INC, ".."); };
use WebminCore;
use Cwd 'abs_path';
use File::Basename;
use File::Find;

&init_config();

our $module_dir = dirname(abs_path(__FILE__));
our $module_config_dir = "/etc/webmin/homelab-backup";
our $config_file = "$module_config_dir/config";
our $log_file = "/opt/backup_homelab.log";
our $system_script = "/opt/backup_homelab.sh";
our $cron_file = "/etc/cron.d/homelab-backup";

if (!-d $module_config_dir) {
    mkdir($module_config_dir, 0755);
}

sub ensure_system_script {
    my $local_script = "$module_dir/backup_homelab.sh";
    if (-f $local_script) {
        system("cp $local_script $system_script >/dev/null 2>&1");
        chmod(0755, $system_script);
    }
}
&ensure_system_script();

# Get backup configuration
sub get_backup_config {
    my %cfg = (
        local_src => "/home/x79",
        temp_dir => "/opt/backups/tmp",
        minio_remote => "minio_local:homelab-backups/",
        cloud_remote => "remote_drive:Homelab_Backups/",
        retention_days => "7",
        enable_remote => "0",
        remote_ip => "",
        remote_port => "22",
        remote_user => "root",
        remote_src => "",
        telegram_bot_token => "",
        telegram_chat_id => "",
        cron_enable => "0",
        cron_schedule => "0 2 * * *",
        enabled_stacks => "ALL"
    );

    if (-f $config_file) {
        open(my $fh, '<', $config_file);
        while (my $line = <$fh>) {
            chomp($line);
            next if ($line =~ /^\s*#/ || $line =~ /^\s*$/);
            if ($line =~ /^\s*([^=]+)\s*=\s*(.*)\s*$/) {
                my ($k, $v) = ($1, $2);
                $k =~ s/^\s+|\s+$//g;
                $v =~ s/^\s+|\s+$//g;
                $cfg{$k} = $v if (defined $k && $k ne "");
            }
        }
        close($fh);
    } elsif (%config) {
        foreach my $k (keys %cfg) {
            $cfg{$k} = $config{$k} if (defined $config{$k} && $config{$k} ne "");
        }
    }

    return \%cfg;
}

# Save backup configuration
sub save_backup_config {
    my ($cfg_ref) = @_;
    open(my $fh, '>', $config_file) or return 0;
    foreach my $k (sort keys %$cfg_ref) {
        print $fh "$k=" . ($cfg_ref->{$k} // "") . "\n";
    }
    close($fh);

    &sync_cron_job($cfg_ref);
    return 1;
}

# Discover Docker Compose Stacks under local_src directory
sub discover_docker_compose_stacks {
    my ($search_dir) = @_;
    $search_dir ||= "/home/x79";
    my @stacks;

    return \@stacks if (!-d $search_dir);

    # Find directories containing docker-compose.yml / compose.yaml
    my %found_dirs;
    find(sub {
        if ($_ =~ /^docker-compose\.ya?ml$/i || $_ =~ /^compose\.ya?ml$/i) {
            $found_dirs{$File::Find::dir} = $File::Find::name;
        }
    }, $search_dir);

    foreach my $dir (sort keys %found_dirs) {
        my $compose_file = $found_dirs{$dir};
        my $name = basename($dir);

        # Check docker container count in this directory
        my $containers = 0;
        my $status = "stopped";
        if (cd_and_run("cd '$dir' && docker compose ps -q 2>/dev/null")) {
            my $ids = `cd '$dir' && docker compose ps -q 2>/dev/null`;
            my @id_list = split(/\s+/, $ids);
            $containers = scalar(@id_list);
            $status = "running" if ($containers > 0);
        }

        push(@stacks, {
            name => $name,
            dir => $dir,
            compose_file => $compose_file,
            status => $status,
            containers => $containers
        });
    }

    return \@stacks;
}

# Helper execution runner
sub cd_and_run {
    my ($cmd) = @_;
    system("$cmd >/dev/null 2>&1");
    return ($? == 0);
}

# Manage Cronjob
sub sync_cron_job {
    my ($cfg_ref) = @_;
    $cfg_ref ||= &get_backup_config();

    if ($cfg_ref->{'cron_enable'} eq '1' && $cfg_ref->{'cron_schedule'}) {
        my $sched = $cfg_ref->{'cron_schedule'};
        my $cron_content = "# Auto-generated by Webmin Homelab Backup Module\n" .
                           "$sched root $system_script >/dev/null 2>&1\n";
        open(my $fh, '>', $cron_file);
        print $fh $cron_content;
        close($fh);
        chmod(0644, $cron_file);
    } else {
        if (-f $cron_file) {
            unlink($cron_file);
        }
    }
}

# Read log file
sub get_logs {
    my ($lines) = @_;
    $lines ||= 150;
    if (!-f $log_file) {
        return "Log file $log_file does not exist yet. Run a backup first.";
    }
    my $out = `tail -n $lines $log_file 2>/dev/null`;
    return $out;
}

# Clear log file
sub clear_logs {
    if (-f $log_file) {
        open(my $fh, '>', $log_file);
        close($fh);
    }
    return 1;
}

# Check if backup script is currently executing
sub is_backup_running {
    my $out = `pgrep -f "backup_homelab.sh" 2>/dev/null`;
    chomp($out);
    return ($out ne '') ? 1 : 0;
}

# Parse last run details from log file
sub get_last_backup_summary {
    return { status => "NEVER", last_run => "N/A" } if (!-f $log_file || -z $log_file);
    
    my $log_text = `cat $log_file 2>/dev/null`;
    my $last_run = "Unknown";
    my @lines = split(/\n/, $log_text);
    foreach my $l (reverse @lines) {
        if ($l =~ /^\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]/) {
            $last_run = $1;
            last;
        }
    }

    my $status = "SUCCESS";
    if ($log_text =~ /FAILED/i || $log_text =~ /CRITICAL/i) {
        $status = "FAILED";
    }
    if (&is_backup_running()) {
        $status = "RUNNING";
    }

    return {
        status => $status,
        last_run => $last_run
    };
}

1;
